http:
  port: "8081"
  
database:
  uhub:
    host: "mysql-148367-0.cloudclusters.net"
    port: "14055"
    user: "admin"
    password: "![j7pMAGRi9pqiE25yAutHOA==]"
    instance: "uhub"

 